/* =====================================================================
   File   : 01_tables.sql - Sequences, XML schema, tables and constraints
   Naming : tables in UPPER_SNAKE_CASE; columns in PascalCase; constraints
            PK_<TABLE>, FK_<CHILD>_<PARENT>, UQ_<TABLE>_<Column>,
            CK_<TABLE>_<Column>, DF_<TABLE>_<Column>
   Time   : instants are UTC - DATETIME columns named ...Utc, DEFAULT
            (GETUTCDATE()); the application converts them to the user's
            time zone. Business dates (DATE) are calendar days of the
            center (UTC+07:00): their DEFAULTs repeat the offset of
            dbo.fn_CenterUtcOffset, because a DEFAULT cannot call a function
            that 02_functions.sql creates later and drops when re-run (T32
            checks that the offsets match).
   What   : the physical schema of QLTTTA (the ERD of docs/DATABASE.md): the sequences that
            generate the IDs, the XML schema of the course syllabuses, the tables with their
            PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK and DEFAULT constraints, and the indexes.
   Order  : second script of db_init (00 -> 07). It expects the empty database of 00 (there is
            no DROP here). A parent table is created before its children because a FOREIGN KEY can
            only reference a table that already exists. Rules that need other rows or other tables
            (no double booking, room of the same branch, free seats, AmountPaid) cannot be CHECK
            constraints; they are the triggers of 05_triggers.sql.
   Defense: - SEQUENCE + DEFAULT: readable IDs such as ST00001 generated by the database (section 1)
            - typed XML: COURSE.SyllabusXml is validated against an XSD (section 2)
            - domain CHECKs (value lists, ranges, phone/email patterns) and cross-column CHECKs that
              compare several columns of the same row (CK_STUDENT_Guardian, CK_ACCOUNT_Owner,
              CK_ENROLLMENT_AmountPaid, CK_RECEIPT_CancelReason ...); a rule "if A then B" is
              written as "(not A) OR B" (CK_TEACHER_Native, CK_PROMOTION_DiscountValue,
              CK_RECEIPT_CancelReason)
            - filtered unique indexes (UX_...): UNIQUE on a column that may be NULL
            - PERSISTED computed columns (TuitionDue, OverallScore, TotalPay) and a stored derived
              attribute kept by a trigger (ENROLLMENT.AmountPaid)
            - recursive relationship: COURSE.PrerequisiteCourseId references COURSE
            - a CHECK constraint rejects a row only when its condition is FALSE; NULL makes the
              condition UNKNOWN, so an optional column left NULL always passes its CHECK
            - time: an instant (when a receipt was paid) is stored in UTC, a business date (the day a
              student registered) as the center's calendar day, so nothing depends on the time zone
              of the server
   ===================================================================== */
USE QLTTTA;
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* ---------------------------------------------------------------------
   1. SEQUENCES that generate the IDs (SQL Server 2012+)
      A SEQUENCE is a database object that hands out the next number (NEXT VALUE FOR).
      The DEFAULT of an ID column (e.g. DF_STUDENT_StudentId) turns that number into a readable
      code: 'ST' + RIGHT('00000' + number, 5) = ST00001. So the database, not the application,
      generates the IDs, and a procedure reads the new ID back with OUTPUT (usp_Student_Add).
      The DEFAULT applies when an INSERT leaves the column out; the seed data inserts fixed
      IDs and then moves the sequence on with ALTER SEQUENCE ... RESTART (07_seed_data.sql).
      The padded part has a fixed width (4 to 6 digits), which limits how many IDs a sequence can
      produce: MAXVALUE is that limit (9999 for EM0001), so the next number fails with a clear error
      instead of RIGHT() cutting 10000 down to EM0000, a code that already exists (test T66).
      Tables with codes chosen by the user (BRANCH, ROOM, PROGRAM, COURSE, PROMOTION)
      have no sequence; technical keys use IDENTITY (GRADE_COMPONENT, CLASS_SESSION, PAYROLL,
      AUDIT_LOG).
   --------------------------------------------------------------------- */
CREATE SEQUENCE dbo.seq_EMPLOYEE       AS INT START WITH 1 INCREMENT BY 1 MAXVALUE 9999   NO CYCLE;
CREATE SEQUENCE dbo.seq_TEACHER        AS INT START WITH 1 INCREMENT BY 1 MAXVALUE 9999   NO CYCLE;
CREATE SEQUENCE dbo.seq_STUDENT        AS INT START WITH 1 INCREMENT BY 1 MAXVALUE 99999  NO CYCLE;
CREATE SEQUENCE dbo.seq_CLASS          AS INT START WITH 1 INCREMENT BY 1 MAXVALUE 9999   NO CYCLE;
CREATE SEQUENCE dbo.seq_ENROLLMENT     AS INT START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NO CYCLE;
CREATE SEQUENCE dbo.seq_RECEIPT        AS INT START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NO CYCLE;
CREATE SEQUENCE dbo.seq_PLACEMENT_TEST AS INT START WITH 1 INCREMENT BY 1 MAXVALUE 99999  NO CYCLE;
CREATE SEQUENCE dbo.seq_CERTIFICATE    AS INT START WITH 1 INCREMENT BY 1 MAXVALUE 99999  NO CYCLE;
GO

/* ---------------------------------------------------------------------
   2. XML SCHEMA COLLECTION for course syllabuses (typed XML)
      The XSD below describes a valid syllabus: a Syllabus root with one or more Textbook
      elements (optional Author and Year attributes), one Objective, then one or more Unit
      elements (required No and Sessions attributes) that each hold a Title and one or more Skill.
      COURSE.SyllabusXml is declared XML (CONTENT dbo.xsc_CourseSyllabus), so SQL Server checks
      every value against this schema and rejects one that does not follow it (test T27). Typed
      XML also knows the data types (No, Sessions and Year are xs:int). The syllabus is read with
      XQuery by usp_Course_FindBySkill, usp_Course_Syllabus and 08_demo_queries.sql.
      TEACHER.ProfileXml and the AUDIT_LOG columns are untyped XML (any well-formed XML).
   --------------------------------------------------------------------- */
CREATE XML SCHEMA COLLECTION dbo.xsc_CourseSyllabus AS N'
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Syllabus">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Textbook" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="Author" type="xs:string" use="optional"/>
                <xs:attribute name="Year" type="xs:int" use="optional"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="Objective" type="xs:string"/>
        <xs:element name="Unit" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Title" type="xs:string"/>
              <xs:element name="Skill" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="No" type="xs:int" use="required"/>
            <xs:attribute name="Sessions" type="xs:int" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>';
GO

/* ---------------------------------------------------------------------
   3. BRANCH - Branches of the center
      One row = one branch; its code (BR01, BR02 ...) is chosen by the user. ROOM, EMPLOYEE,
      TEACHER, STUDENT and CLASS all reference a branch: this is the basis of the horizontal
      fragmentation by branch in 11_distributed_demo.sql. Only Active branches are offered in the
      combo boxes of the application (SqlCatalogRepository).
      CK_BRANCH_Phone: digits only ([^0-9] matches any character that is not a digit, so NOT LIKE
      '%[^0-9]%' means "no such character") and 9 to 11 digits long. CK_BRANCH_Email: a simple
      pattern "x@y.z" (_ = exactly one character, % = any text). EMPLOYEE, TEACHER and STUDENT
      repeat the same two checks.
   --------------------------------------------------------------------- */
CREATE TABLE dbo.BRANCH (
    BranchId    VARCHAR(10)    NOT NULL,
    BranchName  NVARCHAR(100)  NOT NULL,
    Address     NVARCHAR(200)  NOT NULL,
    Phone       VARCHAR(15)    NULL,
    Email       VARCHAR(100)   NULL,
    FoundedOn   DATE           NULL,
    Status      NVARCHAR(20)   NOT NULL CONSTRAINT DF_BRANCH_Status DEFAULT (N'Active'),
    CONSTRAINT PK_BRANCH PRIMARY KEY (BranchId),
    CONSTRAINT UQ_BRANCH_BranchName UNIQUE (BranchName),
    CONSTRAINT CK_BRANCH_Phone CHECK (Phone NOT LIKE '%[^0-9]%' AND LEN(Phone) BETWEEN 9 AND 11),
    CONSTRAINT CK_BRANCH_Email CHECK (Email LIKE '%_@_%._%'),
    CONSTRAINT CK_BRANCH_Status CHECK (Status IN (N'Active', N'Suspended'))
);
GO

/* ---------------------------------------------------------------------
   4. ROOM - Classrooms of a branch
      One row = one classroom of one branch (FK_ROOM_BRANCH).
      UQ_ROOM_BranchId_RoomName: a room name is unique inside its branch only, so two branches may
      use the same room name. Capacity is the upper limit for CLASS.MaxStudents; that rule (and
      "the room belongs to the branch of the class") needs two tables, so trg_CLASS_CheckRoom in
      05_triggers.sql checks it when a class is created or changed.
   --------------------------------------------------------------------- */
CREATE TABLE dbo.ROOM (
    RoomId    VARCHAR(10)   NOT NULL,
    BranchId  VARCHAR(10)   NOT NULL,
    RoomName  NVARCHAR(50)  NOT NULL,
    Capacity  INT           NOT NULL,
    RoomType  NVARCHAR(30)  NOT NULL CONSTRAINT DF_ROOM_RoomType DEFAULT (N'Lecture'),
    Status    NVARCHAR(20)  NOT NULL CONSTRAINT DF_ROOM_Status DEFAULT (N'Available'),
    CONSTRAINT PK_ROOM PRIMARY KEY (RoomId),
    CONSTRAINT FK_ROOM_BRANCH FOREIGN KEY (BranchId) REFERENCES dbo.BRANCH (BranchId),
    CONSTRAINT UQ_ROOM_BranchId_RoomName UNIQUE (BranchId, RoomName),
    CONSTRAINT CK_ROOM_Capacity CHECK (Capacity BETWEEN 1 AND 100),
    CONSTRAINT CK_ROOM_RoomType CHECK (RoomType IN (N'Lecture', N'Lab', N'Multi-purpose')),
    CONSTRAINT CK_ROOM_Status CHECK (Status IN (N'Available', N'Maintenance'))
);
GO

/* ---------------------------------------------------------------------
   5. EMPLOYEE - Office staff (manager, academic staff, accountant, consultant)
      One row = one staff member working at one branch; EmployeeId (EM0001 ...) comes from
      seq_EMPLOYEE through its DEFAULT. An employee may have one sign-in ACCOUNT (roles MANAGER,
      ACADEMIC_STAFF, ACCOUNTANT) and is recorded as the person who enrolled a student
      (ENROLLMENT.EnrolledByEmployeeId) or collected a payment (RECEIPT.CollectedByEmployeeId).
      Phone is required and UNIQUE; Email is optional, so its uniqueness is a filtered unique index.
   --------------------------------------------------------------------- */
CREATE TABLE dbo.EMPLOYEE (
    EmployeeId   VARCHAR(10)    NOT NULL CONSTRAINT DF_EMPLOYEE_EmployeeId
                     DEFAULT ('EM' + RIGHT('0000' + CAST(NEXT VALUE FOR dbo.seq_EMPLOYEE AS VARCHAR(10)), 4)),
    FullName     NVARCHAR(100)  NOT NULL,
    DateOfBirth  DATE           NOT NULL,
    Gender       NVARCHAR(10)   NOT NULL,
    Phone        VARCHAR(15)    NOT NULL,
    Email        VARCHAR(100)   NULL,
    Address      NVARCHAR(200)  NULL,
    Position     NVARCHAR(30)   NOT NULL,
    BranchId     VARCHAR(10)    NOT NULL,
    HireDate     DATE           NOT NULL CONSTRAINT DF_EMPLOYEE_HireDate
                     DEFAULT (CAST(SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00') AS DATE)),
    BaseSalary   DECIMAL(12,0)  NOT NULL CONSTRAINT DF_EMPLOYEE_BaseSalary DEFAULT (0),
    Status       NVARCHAR(20)   NOT NULL CONSTRAINT DF_EMPLOYEE_Status DEFAULT (N'Working'),
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EmployeeId),
    CONSTRAINT FK_EMPLOYEE_BRANCH FOREIGN KEY (BranchId) REFERENCES dbo.BRANCH (BranchId),
    CONSTRAINT UQ_EMPLOYEE_Phone UNIQUE (Phone),
    CONSTRAINT CK_EMPLOYEE_Gender CHECK (Gender IN (N'Male', N'Female', N'Other')),
    CONSTRAINT CK_EMPLOYEE_Phone CHECK (Phone NOT LIKE '%[^0-9]%' AND LEN(Phone) BETWEEN 9 AND 11),
    CONSTRAINT CK_EMPLOYEE_Email CHECK (Email LIKE '%_@_%._%'),
    CONSTRAINT CK_EMPLOYEE_Position CHECK (Position IN (N'Manager', N'Academic staff', N'Accountant', N'Consultant')),
    CONSTRAINT CK_EMPLOYEE_BaseSalary CHECK (BaseSalary >= 0),
    -- Cross-column constraint: an employee must be at least 18 years old when hired
    CONSTRAINT CK_EMPLOYEE_Age CHECK (DATEADD(YEAR, 18, DateOfBirth) <= HireDate),
    CONSTRAINT CK_EMPLOYEE_Status CHECK (Status IN (N'Working', N'Left'))
);
GO
-- UNIQUE on a nullable column: a filtered index (several NULL rows remain valid)
-- A UNIQUE constraint in SQL Server treats NULLs as equal and so allows only ONE row without an
-- email. WHERE Email IS NOT NULL limits the index to the rows that have an email: those must be
-- unique, while any number of employees may have no email. The same idea is used for ACCOUNT and STUDENT.
CREATE UNIQUE INDEX UX_EMPLOYEE_Email ON dbo.EMPLOYEE (Email) WHERE Email IS NOT NULL;
GO

/* ---------------------------------------------------------------------
   6. TEACHER - Teachers (Vietnamese / native speakers), XML profile
      One row = one teacher with a home branch. A teacher is the main teacher of classes
      (CLASS.TeacherId), teaches sessions (CLASS_SESSION.TeacherId), is paid per hour
      (HourlyRate, used by usp_Payroll_Finalize) and may have one ACCOUNT with the role TEACHER.
      Email is required here, so a normal UNIQUE constraint is enough (no filtered index).
      ProfileXml is UNTYPED XML (no schema): certificates with scores, experience and specialties,
      read with XQuery by usp_Teacher_FindByCertificate and 08_demo_queries.sql.
      HourlyRate is sensitive: academic staff get a column-level GRANT without it (06_security.sql).
   --------------------------------------------------------------------- */
CREATE TABLE dbo.TEACHER (
    TeacherId    VARCHAR(10)    NOT NULL CONSTRAINT DF_TEACHER_TeacherId
                     DEFAULT ('TE' + RIGHT('0000' + CAST(NEXT VALUE FOR dbo.seq_TEACHER AS VARCHAR(10)), 4)),
    FullName     NVARCHAR(100)  NOT NULL,
    DateOfBirth  DATE           NOT NULL,
    Gender       NVARCHAR(10)   NOT NULL,
    Nationality  NVARCHAR(50)   NOT NULL CONSTRAINT DF_TEACHER_Nationality DEFAULT (N'Vietnam'),
    Phone        VARCHAR(15)    NOT NULL,
    Email        VARCHAR(100)   NOT NULL,
    Degree       NVARCHAR(20)   NOT NULL,
    TeacherType  NVARCHAR(20)   NOT NULL,
    HourlyRate   DECIMAL(12,0)  NOT NULL,
    ProfileXml   XML            NULL,
    BranchId     VARCHAR(10)    NOT NULL,
    HireDate     DATE           NOT NULL CONSTRAINT DF_TEACHER_HireDate
                     DEFAULT (CAST(SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00') AS DATE)),
    Status       NVARCHAR(20)   NOT NULL CONSTRAINT DF_TEACHER_Status DEFAULT (N'Teaching'),
    CONSTRAINT PK_TEACHER PRIMARY KEY (TeacherId),
    CONSTRAINT FK_TEACHER_BRANCH FOREIGN KEY (BranchId) REFERENCES dbo.BRANCH (BranchId),
    CONSTRAINT UQ_TEACHER_Phone UNIQUE (Phone),
    CONSTRAINT UQ_TEACHER_Email UNIQUE (Email),
    CONSTRAINT CK_TEACHER_Gender CHECK (Gender IN (N'Male', N'Female', N'Other')),
    CONSTRAINT CK_TEACHER_Phone CHECK (Phone NOT LIKE '%[^0-9]%' AND LEN(Phone) BETWEEN 9 AND 11),
    CONSTRAINT CK_TEACHER_Email CHECK (Email LIKE '%_@_%._%'),
    CONSTRAINT CK_TEACHER_Degree CHECK (Degree IN (N'Bachelor', N'Master', N'PhD')),
    CONSTRAINT CK_TEACHER_TeacherType CHECK (TeacherType IN (N'Vietnamese', N'Native')),
    CONSTRAINT CK_TEACHER_HourlyRate CHECK (HourlyRate > 0),
    -- Cross-column constraint: a native-speaker teacher cannot have Vietnamese nationality
    CONSTRAINT CK_TEACHER_Native CHECK (TeacherType = N'Vietnamese' OR Nationality <> N'Vietnam'),
    -- Cross-column constraint: like an employee, a teacher is at least 18 years old when hired
    CONSTRAINT CK_TEACHER_Age CHECK (DATEADD(YEAR, 18, DateOfBirth) <= HireDate),
    CONSTRAINT CK_TEACHER_Status CHECK (Status IN (N'Teaching', N'On leave', N'Left'))
);
GO

/* ---------------------------------------------------------------------
   7. ACCOUNT - Application sign-in accounts.
      Username equals the name of the (contained) database USER;
      passwords are managed by SQL Server (never stored in a table).
      One row = one sign-in account. usp_Account_Create inserts the row AND creates the USER with
      the same name in one transaction, then adds the user to the database role of Role
      (MANAGER -> rl_Manager ...). The signed-in account is found by comparing Username with
      USER_NAME() (fn_CurrentRole, vw_CurrentAccount). Role holds codes without diacritics or
      spaces, so it is VARCHAR. Status Locked goes with DENY CONNECT on the user (usp_Account_Lock).
      CK_ACCOUNT_Owner + the two filtered unique indexes below: an account belongs to exactly one
      person (a TEACHER for the role TEACHER, an EMPLOYEE for every other role) and a person has
      at most one account.
   --------------------------------------------------------------------- */
CREATE TABLE dbo.ACCOUNT (
    Username        NVARCHAR(50)  NOT NULL,
    Role            VARCHAR(20)   NOT NULL,
    EmployeeId      VARCHAR(10)   NULL,
    TeacherId       VARCHAR(10)   NULL,
    Status          NVARCHAR(20)  NOT NULL CONSTRAINT DF_ACCOUNT_Status DEFAULT (N'Active'),
    CreatedAtUtc    DATETIME      NOT NULL CONSTRAINT DF_ACCOUNT_CreatedAtUtc DEFAULT (GETUTCDATE()),
    LastLoginAtUtc  DATETIME      NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (Username),
    CONSTRAINT FK_ACCOUNT_EMPLOYEE FOREIGN KEY (EmployeeId) REFERENCES dbo.EMPLOYEE (EmployeeId),
    CONSTRAINT FK_ACCOUNT_TEACHER FOREIGN KEY (TeacherId) REFERENCES dbo.TEACHER (TeacherId),
    CONSTRAINT CK_ACCOUNT_Role CHECK (Role IN ('MANAGER', 'ACADEMIC_STAFF', 'ACCOUNTANT', 'TEACHER')),
    CONSTRAINT CK_ACCOUNT_Status CHECK (Status IN (N'Active', N'Locked')),
    -- A teacher account belongs to a TEACHER, every other role to an EMPLOYEE
    CONSTRAINT CK_ACCOUNT_Owner CHECK (
        (Role = 'TEACHER' AND TeacherId IS NOT NULL AND EmployeeId IS NULL) OR
        (Role <> 'TEACHER' AND EmployeeId IS NOT NULL AND TeacherId IS NULL))
);
GO
-- One account per person: only the filled column is checked (the other one is NULL)
CREATE UNIQUE INDEX UX_ACCOUNT_EmployeeId ON dbo.ACCOUNT (EmployeeId) WHERE EmployeeId IS NOT NULL;
CREATE UNIQUE INDEX UX_ACCOUNT_TeacherId ON dbo.ACCOUNT (TeacherId) WHERE TeacherId IS NOT NULL;
GO

/* ---------------------------------------------------------------------
   8. STUDENT - Students
      One row = one learner registered at one branch (StudentId ST00001 ... from seq_STUDENT).
      A student takes placement tests and enrolls in many classes (ENROLLMENT). Status starts as
      Prospective; usp_Enrollment_Create sets a Prospective, On hold or Completed student to Studying;
      usp_Class_EvaluateResults sets Completed when the student takes no other class any more.
      Business rule 1 of docs/DATABASE.md, written as CHECK constraints:
        - CK_STUDENT_DateOfBirth: born after 1930-01-01 and at least 4 years old on the
          registration day
        - CK_STUDENT_Guardian (cross-column): a student under 18 on the registration day must have
          a guardian name AND a guardian phone
        - CK_STUDENT_Contact: the student's phone or the guardian's phone must be known
        - Phone and Email are optional but unique when present (filtered unique indexes below)
      Test cases T01 (no guardian) and T02 (phone with letters) of 12_tests.sql prove these checks.
   --------------------------------------------------------------------- */
CREATE TABLE dbo.STUDENT (
    StudentId      VARCHAR(10)    NOT NULL CONSTRAINT DF_STUDENT_StudentId
                       DEFAULT ('ST' + RIGHT('00000' + CAST(NEXT VALUE FOR dbo.seq_STUDENT AS VARCHAR(10)), 5)),
    FullName       NVARCHAR(100)  NOT NULL,
    DateOfBirth    DATE           NOT NULL,
    Gender         NVARCHAR(10)   NOT NULL,
    Phone          VARCHAR(15)    NULL,
    Email          VARCHAR(100)   NULL,
    Address        NVARCHAR(200)  NULL,
    Occupation     NVARCHAR(50)   NULL,
    GuardianName   NVARCHAR(100)  NULL,
    GuardianPhone  VARCHAR(15)    NULL,
    BranchId       VARCHAR(10)    NOT NULL,
    RegisteredOn   DATE           NOT NULL CONSTRAINT DF_STUDENT_RegisteredOn
                       DEFAULT (CAST(SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00') AS DATE)),
    Status         NVARCHAR(20)   NOT NULL CONSTRAINT DF_STUDENT_Status DEFAULT (N'Prospective'),
    Notes          NVARCHAR(500)  NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY (StudentId),
    CONSTRAINT FK_STUDENT_BRANCH FOREIGN KEY (BranchId) REFERENCES dbo.BRANCH (BranchId),
    CONSTRAINT CK_STUDENT_Gender CHECK (Gender IN (N'Male', N'Female', N'Other')),
    CONSTRAINT CK_STUDENT_Phone CHECK (Phone NOT LIKE '%[^0-9]%' AND LEN(Phone) BETWEEN 9 AND 11),
    CONSTRAINT CK_STUDENT_GuardianPhone CHECK (GuardianPhone NOT LIKE '%[^0-9]%' AND LEN(GuardianPhone) BETWEEN 9 AND 11),
    CONSTRAINT CK_STUDENT_Email CHECK (Email LIKE '%_@_%._%'),
    -- Born after 1930-01-01 and at least 4 years old on the registration day
    CONSTRAINT CK_STUDENT_DateOfBirth CHECK (DateOfBirth > '19300101' AND DATEADD(YEAR, 4, DateOfBirth) <= RegisteredOn),
    -- Cross-column constraint: a student under 18 must have guardian details
    CONSTRAINT CK_STUDENT_Guardian CHECK (
        DATEADD(YEAR, 18, DateOfBirth) <= RegisteredOn
        OR (GuardianName IS NOT NULL AND GuardianPhone IS NOT NULL)),
    -- Must be reachable: the student's phone or the guardian's phone
    CONSTRAINT CK_STUDENT_Contact CHECK (Phone IS NOT NULL OR GuardianPhone IS NOT NULL),
    CONSTRAINT CK_STUDENT_Status CHECK (Status IN (N'Prospective', N'Studying', N'On hold', N'Dropped out', N'Completed'))
);
GO
CREATE UNIQUE INDEX UX_STUDENT_Phone ON dbo.STUDENT (Phone) WHERE Phone IS NOT NULL;
CREATE UNIQUE INDEX UX_STUDENT_Email ON dbo.STUDENT (Email) WHERE Email IS NOT NULL;
CREATE INDEX IX_STUDENT_FullName ON dbo.STUDENT (FullName);
GO

/* ---------------------------------------------------------------------
   9. PROGRAM - Training programs (IELTS, TOEIC, Communication, Kids)
      One row = one program; a program consists of one or more courses (COURSE.ProgramId).
   --------------------------------------------------------------------- */
CREATE TABLE dbo.PROGRAM (
    ProgramId       VARCHAR(10)    NOT NULL,
    ProgramName     NVARCHAR(100)  NOT NULL,
    TargetLearners  NVARCHAR(100)  NULL,
    Description     NVARCHAR(500)  NULL,
    CONSTRAINT PK_PROGRAM PRIMARY KEY (ProgramId),
    CONSTRAINT UQ_PROGRAM_ProgramName UNIQUE (ProgramName)
);
GO

/* ---------------------------------------------------------------------
   10. COURSE - Courses (CEFR level), self-reference to the prerequisite
       One row = one course of a program, with its number and length of sessions and its list
       tuition; a course is opened many times as classes (CLASS). Level is a CEFR code from A1
       (beginner) to C2 (mastery). SessionCount tells usp_Class_GenerateSessions how many
       sessions to create for a class.
       Recursive relationship: PrerequisiteCourseId references another COURSE row
       (FK_COURSE_COURSE). CK_COURSE_Prerequisite forbids a course being its own prerequisite
       (only that direct case; a longer cycle is not checked). usp_Enrollment_Create checks the
       entry requirement: the prerequisite course passed OR the latest placement test score at
       least MinPlacementScore.
       SyllabusXml is typed XML (schema collection of section 2); CONTENT (instead of DOCUMENT)
       also accepts a fragment with more than one top-level element.
   --------------------------------------------------------------------- */
CREATE TABLE dbo.COURSE (
    CourseId              VARCHAR(10)    NOT NULL,
    ProgramId             VARCHAR(10)    NOT NULL,
    CourseName            NVARCHAR(100)  NOT NULL,
    Level                 VARCHAR(2)     NOT NULL,
    SessionCount          INT            NOT NULL,
    SessionMinutes        INT            NOT NULL CONSTRAINT DF_COURSE_SessionMinutes DEFAULT (90),
    Tuition               DECIMAL(12,0)  NOT NULL,
    MinPlacementScore     DECIMAL(4,2)   NULL,
    PrerequisiteCourseId  VARCHAR(10)    NULL,
    SyllabusXml           XML (CONTENT dbo.xsc_CourseSyllabus) NULL,
    Status                NVARCHAR(20)   NOT NULL CONSTRAINT DF_COURSE_Status DEFAULT (N'Open'),
    CONSTRAINT PK_COURSE PRIMARY KEY (CourseId),
    CONSTRAINT FK_COURSE_PROGRAM FOREIGN KEY (ProgramId) REFERENCES dbo.PROGRAM (ProgramId),
    CONSTRAINT FK_COURSE_COURSE FOREIGN KEY (PrerequisiteCourseId) REFERENCES dbo.COURSE (CourseId),
    CONSTRAINT UQ_COURSE_CourseName UNIQUE (CourseName),
    CONSTRAINT CK_COURSE_Level CHECK (Level IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')),
    CONSTRAINT CK_COURSE_SessionCount CHECK (SessionCount BETWEEN 1 AND 200),
    CONSTRAINT CK_COURSE_SessionMinutes CHECK (SessionMinutes BETWEEN 30 AND 240),
    CONSTRAINT CK_COURSE_Tuition CHECK (Tuition >= 0),
    CONSTRAINT CK_COURSE_MinPlacementScore CHECK (MinPlacementScore BETWEEN 0 AND 10),
    CONSTRAINT CK_COURSE_Prerequisite CHECK (PrerequisiteCourseId <> CourseId),
    CONSTRAINT CK_COURSE_Status CHECK (Status IN (N'Open', N'Discontinued'))
);
GO

/* ---------------------------------------------------------------------
   11. GRADE_COMPONENT - Grade components and their weights per course
       One row = one graded part of a course and its weight in percent (e.g. Homework 20,
       Midterm 30, Final exam 50). ComponentId is an IDENTITY (a number generated by SQL Server).
       The weights of a course must add up to 100, but a CHECK only sees one row and SQL Server
       has no deferred constraints: the total is listed by the view vw_CourseInvalidWeights, and
       usp_Class_EvaluateResults refuses a course that appears there. fn_FinalGrade then computes
       SUM(Score x Weight) / 100.
   --------------------------------------------------------------------- */
CREATE TABLE dbo.GRADE_COMPONENT (
    ComponentId    INT IDENTITY(1,1)  NOT NULL,
    CourseId       VARCHAR(10)        NOT NULL,
    ComponentName  NVARCHAR(50)       NOT NULL,
    Weight         DECIMAL(5,2)       NOT NULL,
    CONSTRAINT PK_GRADE_COMPONENT PRIMARY KEY (ComponentId),
    CONSTRAINT FK_GRADE_COMPONENT_COURSE FOREIGN KEY (CourseId) REFERENCES dbo.COURSE (CourseId),
    CONSTRAINT UQ_GRADE_COMPONENT_CourseId_ComponentName UNIQUE (CourseId, ComponentName),
    CONSTRAINT CK_GRADE_COMPONENT_Weight CHECK (Weight > 0 AND Weight <= 100)
);
GO

/* ---------------------------------------------------------------------
   12. CLASS - Classes (one run of a course at a branch)
       One row = one class: a course opened at a branch with a main teacher, a main room, a start
       date and a maximum size. Tuition is the price of this class: usp_Class_Create copies
       COURSE.Tuition when no other price is given. EndDate stays NULL until
       usp_Class_GenerateSessions sets it to the date of the last session; until then the overlap
       checks assume a class lasts SessionCount weeks (fn_ClassPeriod, never too short).
       Status: Enrolling -> In progress -> Finished, or Cancelled.
       Rules that need the ROOM table are checked by trg_CLASS_CheckRoom (05_triggers.sql): the
       room belongs to the branch of the class and MaxStudents <= ROOM.Capacity.
       BranchId could be read from the room (RoomId -> ROOM.BranchId), so the table is not in 3NF on
       purpose: the branch of a class is what revenue, filters and permissions group by, and it must
       not follow a room that is later moved. trg_CLASS_CheckRoom and trg_ROOM_CheckClasses keep it equal
       to the branch of the room while the class is active.
   --------------------------------------------------------------------- */
CREATE TABLE dbo.CLASS (
    ClassId      VARCHAR(10)    NOT NULL CONSTRAINT DF_CLASS_ClassId
                     DEFAULT ('CL' + RIGHT('0000' + CAST(NEXT VALUE FOR dbo.seq_CLASS AS VARCHAR(10)), 4)),
    ClassName    NVARCHAR(100)  NOT NULL,
    CourseId     VARCHAR(10)    NOT NULL,
    BranchId     VARCHAR(10)    NOT NULL,
    TeacherId    VARCHAR(10)    NOT NULL,
    RoomId       VARCHAR(10)    NOT NULL,
    StartDate    DATE           NOT NULL,
    EndDate      DATE           NULL,
    MaxStudents  INT            NOT NULL CONSTRAINT DF_CLASS_MaxStudents DEFAULT (20),
    Tuition      DECIMAL(12,0)  NOT NULL,
    Status       NVARCHAR(20)   NOT NULL CONSTRAINT DF_CLASS_Status DEFAULT (N'Enrolling'),
    CONSTRAINT PK_CLASS PRIMARY KEY (ClassId),
    CONSTRAINT FK_CLASS_COURSE FOREIGN KEY (CourseId) REFERENCES dbo.COURSE (CourseId),
    CONSTRAINT FK_CLASS_BRANCH FOREIGN KEY (BranchId) REFERENCES dbo.BRANCH (BranchId),
    CONSTRAINT FK_CLASS_TEACHER FOREIGN KEY (TeacherId) REFERENCES dbo.TEACHER (TeacherId),
    CONSTRAINT FK_CLASS_ROOM FOREIGN KEY (RoomId) REFERENCES dbo.ROOM (RoomId),
    CONSTRAINT CK_CLASS_MaxStudents CHECK (MaxStudents BETWEEN 1 AND 50),
    CONSTRAINT CK_CLASS_Tuition CHECK (Tuition >= 0),
    CONSTRAINT CK_CLASS_Dates CHECK (EndDate IS NULL OR EndDate >= StartDate),
    CONSTRAINT CK_CLASS_Status CHECK (Status IN (N'Enrolling', N'In progress', N'Finished', N'Cancelled'))
);
GO
CREATE INDEX IX_CLASS_CourseId ON dbo.CLASS (CourseId);
CREATE INDEX IX_CLASS_TeacherId ON dbo.CLASS (TeacherId);
GO

/* ---------------------------------------------------------------------
   13. CLASS_SCHEDULE - Fixed weekly timetable of a class
       (Weekday: ISO 8601, 1 = Monday ... 7 = Sunday)
       One row = one weekly time slot of a class (e.g. Monday 18:00-19:30).
       PRIMARY KEY (ClassId, Weekday): at most one slot per weekday for a class.
       ON DELETE CASCADE: deleting a class deletes its timetable too.
       CK_CLASS_SCHEDULE_Time (cross-column): the slot ends after it starts, inside 07:00-22:00.
       No double booking of a room or a teacher between active classes is a rule across rows and
       tables: trg_CLASS_SCHEDULE_CheckConflict (05_triggers.sql, test T08).
   --------------------------------------------------------------------- */
CREATE TABLE dbo.CLASS_SCHEDULE (
    ClassId    VARCHAR(10)  NOT NULL,
    Weekday    TINYINT      NOT NULL,
    StartTime  TIME(0)      NOT NULL,
    EndTime    TIME(0)      NOT NULL,
    CONSTRAINT PK_CLASS_SCHEDULE PRIMARY KEY (ClassId, Weekday),
    CONSTRAINT FK_CLASS_SCHEDULE_CLASS FOREIGN KEY (ClassId) REFERENCES dbo.CLASS (ClassId) ON DELETE CASCADE,
    CONSTRAINT CK_CLASS_SCHEDULE_Weekday CHECK (Weekday BETWEEN 1 AND 7),
    CONSTRAINT CK_CLASS_SCHEDULE_Time CHECK (EndTime > StartTime AND StartTime >= '07:00' AND EndTime <= '22:00')
);
GO

/* ---------------------------------------------------------------------
   14. CLASS_SESSION - Individual sessions (generated from CLASS_SCHEDULE)
       One row = one dated lesson of a class. usp_Class_GenerateSessions creates COURSE.SessionCount
       sessions on the weekdays of the timetable, numbered 1, 2, 3 ... (UQ_CLASS_SESSION_ClassId_SessionNo).
       Date, time, room and teacher are stored per session, not only on CLASS: attendance and the
       payroll (usp_Payroll_Finalize counts the taught sessions of each teacher) work per session.
       Once a session is Taught, trg_CLASS_SESSION_LockTaught freezes its date, time, room and teacher.
       SessionId is an IDENTITY, the short key that ATTENDANCE references.
       IX_CLASS_SESSION_SessionDate: index for searches by date (timetables, sessions today); INCLUDE
       also stores the listed columns in the index, so such a query needs fewer lookups in the table.
   --------------------------------------------------------------------- */
CREATE TABLE dbo.CLASS_SESSION (
    SessionId    INT IDENTITY(1,1)  NOT NULL,
    ClassId      VARCHAR(10)        NOT NULL,
    SessionNo    INT                NOT NULL,
    SessionDate  DATE               NOT NULL,
    StartTime    TIME(0)            NOT NULL,
    EndTime      TIME(0)            NOT NULL,
    RoomId       VARCHAR(10)        NOT NULL,
    TeacherId    VARCHAR(10)        NOT NULL,
    Description  NVARCHAR(200)      NULL,
    Status       NVARCHAR(20)       NOT NULL CONSTRAINT DF_CLASS_SESSION_Status DEFAULT (N'Scheduled'),
    CONSTRAINT PK_CLASS_SESSION PRIMARY KEY (SessionId),
    CONSTRAINT FK_CLASS_SESSION_CLASS FOREIGN KEY (ClassId) REFERENCES dbo.CLASS (ClassId) ON DELETE CASCADE,
    CONSTRAINT FK_CLASS_SESSION_ROOM FOREIGN KEY (RoomId) REFERENCES dbo.ROOM (RoomId),
    CONSTRAINT FK_CLASS_SESSION_TEACHER FOREIGN KEY (TeacherId) REFERENCES dbo.TEACHER (TeacherId),
    CONSTRAINT UQ_CLASS_SESSION_ClassId_SessionNo UNIQUE (ClassId, SessionNo),
    CONSTRAINT CK_CLASS_SESSION_SessionNo CHECK (SessionNo >= 1),
    CONSTRAINT CK_CLASS_SESSION_Time CHECK (EndTime > StartTime),
    CONSTRAINT CK_CLASS_SESSION_Status CHECK (Status IN (N'Scheduled', N'Taught', N'Cancelled'))
);
GO
CREATE INDEX IX_CLASS_SESSION_SessionDate ON dbo.CLASS_SESSION (SessionDate)
    INCLUDE (ClassId, TeacherId, RoomId, StartTime, EndTime);
-- The sessions of one teacher in a date range: the teacher views and usp_Payroll_Finalize
CREATE INDEX IX_CLASS_SESSION_TeacherId_SessionDate ON dbo.CLASS_SESSION (TeacherId, SessionDate)
    INCLUDE (Status, StartTime, EndTime);
GO

/* ---------------------------------------------------------------------
   15. PROMOTION - Tuition promotions
       One row = one discount campaign valid from StartDate to EndDate. DiscountType PERCENT means
       DiscountValue is a percentage; AMOUNT means it is a fixed amount in VND.
       CK_PROMOTION_DiscountValue (cross-column): the value is positive and a percentage is at most 50.
       The discount of an enrollment is computed by fn_DiscountAmount and stored in
       ENROLLMENT.DiscountAmount.
   --------------------------------------------------------------------- */
CREATE TABLE dbo.PROMOTION (
    PromotionId    VARCHAR(10)    NOT NULL,
    PromotionName  NVARCHAR(100)  NOT NULL,
    DiscountType   VARCHAR(10)    NOT NULL,
    DiscountValue  DECIMAL(12,2)  NOT NULL,
    StartDate      DATE           NOT NULL,
    EndDate        DATE           NOT NULL,
    CONSTRAINT PK_PROMOTION PRIMARY KEY (PromotionId),
    CONSTRAINT CK_PROMOTION_DiscountType CHECK (DiscountType IN ('PERCENT', 'AMOUNT')),
    -- Cross-column: always positive, and "if PERCENT then at most 50" written as (not PERCENT) OR <= 50
    CONSTRAINT CK_PROMOTION_DiscountValue CHECK (DiscountValue > 0 AND (DiscountType <> 'PERCENT' OR DiscountValue <= 50)),
    CONSTRAINT CK_PROMOTION_Dates CHECK (EndDate >= StartDate)
);
GO

/* ---------------------------------------------------------------------
   16. ENROLLMENT - A student enrolled in a class (n-n STUDENT - CLASS)
       AmountPaid is a derived attribute = SUM(RECEIPT.Amount) of the valid receipts, kept by a
       trigger (trg_RECEIPT_UpdateAmountPaid).
       One row = one student in one class. It turns the many-to-many relationship STUDENT - CLASS
       into two one-to-many relationships and holds what belongs to the pair: tuition, payments,
       attendance (ATTENDANCE), grades (GRADE), final result and certificate.
       UQ_ENROLLMENT_StudentId_ClassId: a student enrolls in a class only once (usp_Enrollment_Create
       checks it first with a clear message, test T03; the constraint is the last guard).
       Money columns:
         - BaseTuition: CLASS.Tuition copied at enrollment time (usp_Enrollment_Create), so a later
           price change of the class does not change what this student owes
         - DiscountAmount: from the promotion (fn_DiscountAmount), never above BaseTuition
         - TuitionDue: computed column BaseTuition - DiscountAmount; PERSISTED stores the value in
           the row and SQL Server recomputes it whenever one of the two columns changes
         - AmountPaid: stored rather than summed on every read, so lists and balances
           (vw_OutstandingTuition, fn_StudentBalance) read it directly, and CK_ENROLLMENT_AmountPaid
           can forbid paying more than TuitionDue (a backup of the check in the trigger, test T06)
       Dates: EnrolledOn is the day of the enrollment (promotions are valid on it); ClassJoinedOn is the day
       the student started in the CURRENT class - EnrolledOn at enrollment, the transfer day after
       usp_Enrollment_TransferClass - so fn_AttendanceRate only counts the sessions of the class since then
       (CK_ENROLLMENT_ClassJoinedOn: never before EnrolledOn).
       FinalGrade and Result stay NULL until usp_Class_EvaluateResults writes them at the end of
       the course, together with Status Completed (CK_ENROLLMENT_Completed: a result exactly for a completed
       enrollment). Free seats: trg_ENROLLMENT_CheckCapacity (it needs the CLASS table).
   --------------------------------------------------------------------- */
CREATE TABLE dbo.ENROLLMENT (
    EnrollmentId          VARCHAR(10)    NOT NULL CONSTRAINT DF_ENROLLMENT_EnrollmentId
                              DEFAULT ('EN' + RIGHT('000000' + CAST(NEXT VALUE FOR dbo.seq_ENROLLMENT AS VARCHAR(10)), 6)),
    StudentId             VARCHAR(10)    NOT NULL,
    ClassId               VARCHAR(10)    NOT NULL,
    EnrolledOn            DATE           NOT NULL CONSTRAINT DF_ENROLLMENT_EnrolledOn
                              DEFAULT (CAST(SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00') AS DATE)),
    ClassJoinedOn         DATE           NOT NULL CONSTRAINT DF_ENROLLMENT_ClassJoinedOn
                              DEFAULT (CAST(SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00') AS DATE)),
    BaseTuition           DECIMAL(12,0)  NOT NULL,
    PromotionId           VARCHAR(10)    NULL,
    DiscountAmount        DECIMAL(12,0)  NOT NULL CONSTRAINT DF_ENROLLMENT_DiscountAmount DEFAULT (0),
    TuitionDue            AS (BaseTuition - DiscountAmount) PERSISTED,
    AmountPaid            DECIMAL(12,0)  NOT NULL CONSTRAINT DF_ENROLLMENT_AmountPaid DEFAULT (0),
    Status                NVARCHAR(20)   NOT NULL CONSTRAINT DF_ENROLLMENT_Status DEFAULT (N'Studying'),
    FinalGrade            DECIMAL(4,2)   NULL,
    Result                NVARCHAR(20)   NULL,
    EnrolledByEmployeeId  VARCHAR(10)    NULL,
    CONSTRAINT PK_ENROLLMENT PRIMARY KEY (EnrollmentId),
    CONSTRAINT FK_ENROLLMENT_STUDENT FOREIGN KEY (StudentId) REFERENCES dbo.STUDENT (StudentId),
    CONSTRAINT FK_ENROLLMENT_CLASS FOREIGN KEY (ClassId) REFERENCES dbo.CLASS (ClassId),
    CONSTRAINT FK_ENROLLMENT_PROMOTION FOREIGN KEY (PromotionId) REFERENCES dbo.PROMOTION (PromotionId),
    CONSTRAINT FK_ENROLLMENT_EMPLOYEE FOREIGN KEY (EnrolledByEmployeeId) REFERENCES dbo.EMPLOYEE (EmployeeId),
    CONSTRAINT UQ_ENROLLMENT_StudentId_ClassId UNIQUE (StudentId, ClassId),
    CONSTRAINT CK_ENROLLMENT_ClassJoinedOn CHECK (ClassJoinedOn >= EnrolledOn),
    CONSTRAINT CK_ENROLLMENT_BaseTuition CHECK (BaseTuition >= 0),
    CONSTRAINT CK_ENROLLMENT_DiscountAmount CHECK (DiscountAmount >= 0 AND DiscountAmount <= BaseTuition),
    -- Cross-column constraint: the amount paid never exceeds the tuition due
    CONSTRAINT CK_ENROLLMENT_AmountPaid CHECK (AmountPaid >= 0 AND AmountPaid <= BaseTuition - DiscountAmount),
    CONSTRAINT CK_ENROLLMENT_Status CHECK (Status IN (N'Studying', N'On hold', N'Left', N'Completed')),
    CONSTRAINT CK_ENROLLMENT_FinalGrade CHECK (FinalGrade BETWEEN 0 AND 10),
    CONSTRAINT CK_ENROLLMENT_Result CHECK (Result IN (N'Passed', N'Failed')),
    -- Cross-column constraint: the evaluation writes Status, Result and FinalGrade together
    CONSTRAINT CK_ENROLLMENT_Completed CHECK ((Status = N'Completed' AND Result IS NOT NULL)
                                              OR (Status <> N'Completed' AND Result IS NULL AND FinalGrade IS NULL))
);
GO
CREATE INDEX IX_ENROLLMENT_ClassId ON dbo.ENROLLMENT (ClassId) INCLUDE (StudentId, Status);
GO

/* ---------------------------------------------------------------------
   17. RECEIPT - Tuition receipts (one enrollment may be paid in installments)
       One row = one payment for one enrollment, collected by an employee.
       Receipts are never deleted (trg_RECEIPT_PreventDelete, plus DENY DELETE even for the
       manager): a wrong receipt is cancelled by usp_Receipt_Cancel, so the financial history stays
       complete. CK_RECEIPT_CancelReason (cross-column): a cancelled receipt must say why.
       Every new or cancelled receipt recomputes ENROLLMENT.AmountPaid (trg_RECEIPT_UpdateAmountPaid)
       and is written to AUDIT_LOG (trg_RECEIPT_Audit).
       PaidAtUtc is the payment instant in UTC; reports turn local days/months into UTC ranges.
       IX_RECEIPT_PaidAtUtc: index for those range queries (usp_Report_Revenue, usp_Dashboard_Stats,
       fn_MonthlyRevenue).
   --------------------------------------------------------------------- */
CREATE TABLE dbo.RECEIPT (
    ReceiptId              VARCHAR(10)    NOT NULL CONSTRAINT DF_RECEIPT_ReceiptId
                               DEFAULT ('RC' + RIGHT('000000' + CAST(NEXT VALUE FOR dbo.seq_RECEIPT AS VARCHAR(10)), 6)),
    EnrollmentId           VARCHAR(10)    NOT NULL,
    PaidAtUtc              DATETIME       NOT NULL CONSTRAINT DF_RECEIPT_PaidAtUtc DEFAULT (GETUTCDATE()),
    Amount                 DECIMAL(12,0)  NOT NULL,
    PaymentMethod          NVARCHAR(20)   NOT NULL CONSTRAINT DF_RECEIPT_PaymentMethod DEFAULT (N'Cash'),
    CollectedByEmployeeId  VARCHAR(10)    NOT NULL,
    Description            NVARCHAR(200)  NULL,
    Status                 NVARCHAR(20)   NOT NULL CONSTRAINT DF_RECEIPT_Status DEFAULT (N'Valid'),
    CancelReason           NVARCHAR(200)  NULL,
    CONSTRAINT PK_RECEIPT PRIMARY KEY (ReceiptId),
    CONSTRAINT FK_RECEIPT_ENROLLMENT FOREIGN KEY (EnrollmentId) REFERENCES dbo.ENROLLMENT (EnrollmentId),
    CONSTRAINT FK_RECEIPT_EMPLOYEE FOREIGN KEY (CollectedByEmployeeId) REFERENCES dbo.EMPLOYEE (EmployeeId),
    CONSTRAINT CK_RECEIPT_Amount CHECK (Amount > 0),
    CONSTRAINT CK_RECEIPT_PaymentMethod CHECK (PaymentMethod IN (N'Cash', N'Bank transfer', N'Card')),
    CONSTRAINT CK_RECEIPT_Status CHECK (Status IN (N'Valid', N'Cancelled')),
    -- Cross-column: a receipt that is not Valid (= Cancelled) must have a CancelReason
    CONSTRAINT CK_RECEIPT_CancelReason CHECK (Status = N'Valid' OR CancelReason IS NOT NULL)
);
GO
CREATE INDEX IX_RECEIPT_EnrollmentId ON dbo.RECEIPT (EnrollmentId) INCLUDE (Amount, Status);
CREATE INDEX IX_RECEIPT_PaidAtUtc ON dbo.RECEIPT (PaidAtUtc) INCLUDE (Amount, Status, EnrollmentId);
GO

/* ---------------------------------------------------------------------
   18. ATTENDANCE - Attendance of a student at a session
       One row = the mark of one enrollment at one session; PRIMARY KEY (SessionId, EnrollmentId)
       allows one mark per student per session. No row means "not marked yet" (usp_Attendance_BySession
       shows such a student as Present by default). fn_AttendanceRate counts Present and Late as attended.
       The enrollment must belong to the class of the session: that needs two other tables, so
       trg_ATTENDANCE_CheckClass checks it.
       ON DELETE CASCADE from CLASS_SESSION: when the sessions of a class are regenerated (only
       possible while all are still Scheduled), their attendance rows are deleted with them.
   --------------------------------------------------------------------- */
CREATE TABLE dbo.ATTENDANCE (
    SessionId     INT            NOT NULL,
    EnrollmentId  VARCHAR(10)    NOT NULL,
    Status        NVARCHAR(20)   NOT NULL CONSTRAINT DF_ATTENDANCE_Status DEFAULT (N'Present'),
    Notes         NVARCHAR(200)  NULL,
    CONSTRAINT PK_ATTENDANCE PRIMARY KEY (SessionId, EnrollmentId),
    CONSTRAINT FK_ATTENDANCE_CLASS_SESSION FOREIGN KEY (SessionId) REFERENCES dbo.CLASS_SESSION (SessionId) ON DELETE CASCADE,
    CONSTRAINT FK_ATTENDANCE_ENROLLMENT FOREIGN KEY (EnrollmentId) REFERENCES dbo.ENROLLMENT (EnrollmentId),
    CONSTRAINT CK_ATTENDANCE_Status CHECK (Status IN (N'Present', N'Late', N'Excused absence', N'Unexcused absence'))
);
GO
-- The primary key starts with SessionId; the marks of one enrollment (fn_AttendanceRate, the class transfer, the
-- foreign key check when an enrollment changes) need their own index
CREATE INDEX IX_ATTENDANCE_EnrollmentId ON dbo.ATTENDANCE (EnrollmentId) INCLUDE (Status);
GO

/* ---------------------------------------------------------------------
   19. GRADE - Score of a student for each grade component of a class
       One row = the score (0-10) of one enrollment for one grade component of the course;
       PRIMARY KEY (EnrollmentId, ComponentId): one score per component, a correction is an UPDATE
       (usp_Grade_Save). EnteredBy DEFAULT ORIGINAL_LOGIN(): the name the person signed in with
       (for a contained user, the user name), even inside EXECUTE AS.
       The component must belong to the course of the class (trg_GRADE_CheckComponent) and every
       change is logged as XML in AUDIT_LOG (trg_GRADE_Audit).
   --------------------------------------------------------------------- */
CREATE TABLE dbo.GRADE (
    EnrollmentId  VARCHAR(10)    NOT NULL,
    ComponentId   INT            NOT NULL,
    Score         DECIMAL(4,2)   NOT NULL,
    EnteredAtUtc  DATETIME       NOT NULL CONSTRAINT DF_GRADE_EnteredAtUtc DEFAULT (GETUTCDATE()),
    EnteredBy     NVARCHAR(128)  NOT NULL CONSTRAINT DF_GRADE_EnteredBy DEFAULT (ORIGINAL_LOGIN()),
    CONSTRAINT PK_GRADE PRIMARY KEY (EnrollmentId, ComponentId),
    CONSTRAINT FK_GRADE_ENROLLMENT FOREIGN KEY (EnrollmentId) REFERENCES dbo.ENROLLMENT (EnrollmentId),
    CONSTRAINT FK_GRADE_GRADE_COMPONENT FOREIGN KEY (ComponentId) REFERENCES dbo.GRADE_COMPONENT (ComponentId),
    CONSTRAINT CK_GRADE_Score CHECK (Score BETWEEN 0 AND 10)
);
GO

/* ---------------------------------------------------------------------
   20. PLACEMENT_TEST - Placement test before enrolling (4 skills)
       One row = one test taken by a student, with a score (0-10) for each of the four skills.
       OverallScore: PERSISTED computed column = the average of the four skills (2 decimals).
       RecommendedCourseId is filled automatically by trg_PLACEMENT_TEST_Recommend with
       fn_RecommendCourse. usp_Enrollment_Create uses the latest test of the student for the
       entry requirement of a course (OverallScore >= COURSE.MinPlacementScore).
   --------------------------------------------------------------------- */
CREATE TABLE dbo.PLACEMENT_TEST (
    TestId               VARCHAR(10)    NOT NULL CONSTRAINT DF_PLACEMENT_TEST_TestId
                             DEFAULT ('PT' + RIGHT('00000' + CAST(NEXT VALUE FOR dbo.seq_PLACEMENT_TEST AS VARCHAR(10)), 5)),
    StudentId            VARCHAR(10)    NOT NULL,
    TestDate             DATE           NOT NULL CONSTRAINT DF_PLACEMENT_TEST_TestDate
                             DEFAULT (CAST(SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00') AS DATE)),
    ListeningScore       DECIMAL(4,2)   NOT NULL,
    SpeakingScore        DECIMAL(4,2)   NOT NULL,
    ReadingScore         DECIMAL(4,2)   NOT NULL,
    WritingScore         DECIMAL(4,2)   NOT NULL,
    OverallScore         AS CAST((ListeningScore + SpeakingScore + ReadingScore + WritingScore) / 4 AS DECIMAL(4,2)) PERSISTED,
    RecommendedCourseId  VARCHAR(10)    NULL,
    GradedByTeacherId    VARCHAR(10)    NULL,
    Notes                NVARCHAR(200)  NULL,
    CONSTRAINT PK_PLACEMENT_TEST PRIMARY KEY (TestId),
    CONSTRAINT FK_PLACEMENT_TEST_STUDENT FOREIGN KEY (StudentId) REFERENCES dbo.STUDENT (StudentId),
    CONSTRAINT FK_PLACEMENT_TEST_COURSE FOREIGN KEY (RecommendedCourseId) REFERENCES dbo.COURSE (CourseId),
    CONSTRAINT FK_PLACEMENT_TEST_TEACHER FOREIGN KEY (GradedByTeacherId) REFERENCES dbo.TEACHER (TeacherId),
    CONSTRAINT CK_PLACEMENT_TEST_Scores CHECK (
        ListeningScore BETWEEN 0 AND 10 AND SpeakingScore BETWEEN 0 AND 10 AND
        ReadingScore   BETWEEN 0 AND 10 AND WritingScore  BETWEEN 0 AND 10)
);
GO
-- The latest test of a student (usp_Enrollment_Create: TOP (1) ... ORDER BY TestDate DESC, TestId DESC)
CREATE INDEX IX_PLACEMENT_TEST_StudentId ON dbo.PLACEMENT_TEST (StudentId, TestDate DESC, TestId DESC)
    INCLUDE (OverallScore);
GO

/* ---------------------------------------------------------------------
   21. CERTIFICATE - Course completion certificates issued by the center
       One row = the certificate of one passed enrollment; UQ_CERTIFICATE_EnrollmentId allows at
       most one per enrollment (a one-to-one relationship with ENROLLMENT). usp_Class_EvaluateResults
       creates it with the serial number EC<year>-<EnrollmentId>. FinalGrade and Classification are
       copied at issue time, so the certificate keeps the values it was issued with.
       CK_CERTIFICATE_FinalGrade (5-10): only a passing grade gets a certificate; the rule "the
       enrollment Result is Passed" needs ENROLLMENT, so trg_CERTIFICATE_CheckResult checks it.
   --------------------------------------------------------------------- */
CREATE TABLE dbo.CERTIFICATE (
    CertificateId   VARCHAR(10)   NOT NULL CONSTRAINT DF_CERTIFICATE_CertificateId
                        DEFAULT ('CE' + RIGHT('00000' + CAST(NEXT VALUE FOR dbo.seq_CERTIFICATE AS VARCHAR(10)), 5)),
    EnrollmentId    VARCHAR(10)   NOT NULL,
    SerialNumber    VARCHAR(20)   NOT NULL,
    IssuedOn        DATE          NOT NULL CONSTRAINT DF_CERTIFICATE_IssuedOn
                        DEFAULT (CAST(SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00') AS DATE)),
    FinalGrade      DECIMAL(4,2)  NOT NULL,
    Classification  NVARCHAR(20)  NOT NULL,
    CONSTRAINT PK_CERTIFICATE PRIMARY KEY (CertificateId),
    CONSTRAINT FK_CERTIFICATE_ENROLLMENT FOREIGN KEY (EnrollmentId) REFERENCES dbo.ENROLLMENT (EnrollmentId),
    CONSTRAINT UQ_CERTIFICATE_EnrollmentId UNIQUE (EnrollmentId),
    CONSTRAINT UQ_CERTIFICATE_SerialNumber UNIQUE (SerialNumber),
    CONSTRAINT CK_CERTIFICATE_FinalGrade CHECK (FinalGrade BETWEEN 5 AND 10),
    CONSTRAINT CK_CERTIFICATE_Classification CHECK (Classification IN (N'Excellent', N'Very good', N'Good', N'Average'))
);
GO

/* ---------------------------------------------------------------------
   22. PAYROLL - Monthly teacher payroll (finalized with a cursor)
       One row = the pay of one teacher for one month (UQ_PAYROLL_TeacherId_Month_Year).
       Written by usp_Payroll_Finalize: SessionCount and Hours come from the taught sessions of the
       month; HourlyRate is copied from TEACHER, so a later rate change does not alter a Paid month.
       TotalPay: PERSISTED computed column = Hours x HourlyRate + Bonus - Deduction.
       Status Finalized can still be recomputed by finalizing the month again (with the rate of that day);
       a Paid row is left as is. CK_PAYROLL_Deduction keeps TotalPay at 0 or more, also when a month finalized
       again gets a lower rate under a deduction set earlier (usp_Payroll_Adjust checks it first, 50053).
       Teachers see only their own rows, through vw_Teacher_MyPay.
   --------------------------------------------------------------------- */
CREATE TABLE dbo.PAYROLL (
    PayrollId       INT IDENTITY(1,1)  NOT NULL,
    TeacherId       VARCHAR(10)        NOT NULL,
    Month           TINYINT            NOT NULL,
    Year            SMALLINT           NOT NULL,
    SessionCount    INT                NOT NULL,
    Hours           DECIMAL(6,2)       NOT NULL,
    HourlyRate      DECIMAL(12,0)      NOT NULL,
    Bonus           DECIMAL(12,0)      NOT NULL CONSTRAINT DF_PAYROLL_Bonus DEFAULT (0),
    Deduction       DECIMAL(12,0)      NOT NULL CONSTRAINT DF_PAYROLL_Deduction DEFAULT (0),
    TotalPay        AS (CAST(Hours * HourlyRate AS DECIMAL(14,0)) + Bonus - Deduction) PERSISTED,
    FinalizedAtUtc  DATETIME           NOT NULL CONSTRAINT DF_PAYROLL_FinalizedAtUtc DEFAULT (GETUTCDATE()),
    Status          NVARCHAR(20)       NOT NULL CONSTRAINT DF_PAYROLL_Status DEFAULT (N'Finalized'),
    CONSTRAINT PK_PAYROLL PRIMARY KEY (PayrollId),
    CONSTRAINT FK_PAYROLL_TEACHER FOREIGN KEY (TeacherId) REFERENCES dbo.TEACHER (TeacherId),
    CONSTRAINT UQ_PAYROLL_TeacherId_Month_Year UNIQUE (TeacherId, Month, Year),
    CONSTRAINT CK_PAYROLL_Month CHECK (Month BETWEEN 1 AND 12),
    CONSTRAINT CK_PAYROLL_Year CHECK (Year >= 2020),
    CONSTRAINT CK_PAYROLL_Figures CHECK (SessionCount >= 0 AND Hours >= 0 AND Bonus >= 0 AND Deduction >= 0),
    CONSTRAINT CK_PAYROLL_Deduction CHECK (Deduction <= CAST(Hours * HourlyRate AS DECIMAL(14,0)) + Bonus),
    CONSTRAINT CK_PAYROLL_Status CHECK (Status IN (N'Finalized', N'Paid'))
);
GO

/* ---------------------------------------------------------------------
   23. AUDIT_LOG - Audit trail, written by triggers
       One row = one change of a GRADE, RECEIPT or PAYROLL row (trg_GRADE_Audit, trg_RECEIPT_Audit,
       trg_PAYROLL_Audit), with the old and new values as untyped XML built with FOR XML PATH. PerformedBy DEFAULT ORIGINAL_LOGIN()
       records who really made the change. The log is append-only: trg_AUDIT_LOG_ReadOnly
       (INSTEAD OF UPDATE, DELETE) plus DENY UPDATE, DELETE even for the manager (06_security.sql).
   --------------------------------------------------------------------- */
CREATE TABLE dbo.AUDIT_LOG (
    LogId        BIGINT IDENTITY(1,1)  NOT NULL,
    LoggedAtUtc  DATETIME              NOT NULL CONSTRAINT DF_AUDIT_LOG_LoggedAtUtc DEFAULT (GETUTCDATE()),
    PerformedBy  NVARCHAR(128)         NOT NULL CONSTRAINT DF_AUDIT_LOG_PerformedBy DEFAULT (ORIGINAL_LOGIN()),
    TableName    NVARCHAR(50)          NOT NULL,
    Action       VARCHAR(10)           NOT NULL,
    RecordKey    NVARCHAR(100)         NOT NULL,
    OldData      XML                   NULL,
    NewData      XML                   NULL,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (LogId),
    CONSTRAINT CK_AUDIT_LOG_Action CHECK (Action IN ('INSERT', 'UPDATE', 'DELETE'))
);
GO
