#pragma once

#include <QCoreApplication>
#include <QDate>
#include <QString>
#include <QStringList>

// Valid values - identical to the CHECK constraints of table STUDENT.
// These are the values STORED in the database (language-neutral codes, written in English);
// DbValues::label (presentation) turns them into display text in the UI language.
namespace StudentValues {
QStringList genders();  // Male, Female, Other
QStringList statuses(); // Prospective, Studying, On hold, Dropped out
QString activeStatus(); // "Studying"
} // namespace StudentValues

// Student entity (table STUDENT) plus a few aggregated fields shown in the list.
// One field per column, same names in camelCase (FullName -> fullName). A struct is a plain record: the data
// travels through every layer (form -> StudentService -> SqlStudentRepository -> usp_Student_* procedures).
struct Student {
    QString id; // StudentId, generated by the database (ST00001...); empty for a student not saved yet
    QString fullName;
    QDate dateOfBirth;
    QString gender = QStringLiteral("Male");
    QString phone;
    QString email;
    QString address;
    QString occupation;
    QString guardianName;
    QString guardianPhone;
    QString branchId;
    QDate registeredOn; // empty for a new student: usp_Student_Add then uses today's date
    // A new student starts as Prospective, like the default DF_STUDENT_Status of the database
    QString status = QStringLiteral("Prospective");
    QString notes;

    // Display only (from view vw_StudentOverview)
    QString branchName;
    int activeClassCount = 0;
    qint64 outstandingBalance = 0;

    int age(const QDate& asOf) const;            // full years on that date (0 if a date is missing)
    bool needsGuardian(const QDate& asOf) const; // under 18 on that date => guardian name + phone required

    // Business rules checked in the application for fast feedback.
    // The database remains the final check (CHECK constraints, triggers, procedures).
    // Messages are translated into the UI language when created (tr() is Qt Core, no UI dependency).
    QStringList validate(const QDate& today) const;

    // Declares tr() with translation context "Student". The macro ends with "private:", so keep it last.
    Q_DECLARE_TR_FUNCTIONS(Student)
};

// Student search criteria
struct StudentFilter {
    QString keyword;
    QString branchId; // empty = all branches
    QString status;   // empty = all statuses
};
